# Site settings
title: Android Kotlin Guides
email: fythonx@gmail.com
description: >
  在 Android 上开发 Kotlin 的官方指导
baseurl: "/kotlin-guides-cn"
url: "https://fython.github.io"

# Build settings
markdown: kramdown

collections:
  - changes

plugins:
  - octopress-autoprefixer
  - jekyll-redirect-from

exclude:
  - vendor
